name: Release
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  report-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Report commit to Ultralight
        id: ul-report-commit
        uses: ultralightlabs/ultralight-github-action@v1.3.2-canary.0
        with:
          ultralight-api-key: ${{secrets.ULTRALIGHT_GH_ACTION_SECRET_KEY}}
          ultralight-url: https://staging.ultralightlabs.com
          command: REPORT_COMMIT

      - name: test next step
        run: |
          echo "${{ steps.ul-report-commit.outputs.merge-block }}"
          echo "${{ steps.ul-report-commit.outputs.report-commit-data }}"
