name: Release Pull Request
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  # pull_request_review:
  #   types: [submitted]
jobs:
  report-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Report commit to Ultralight
        id: report-commit
        uses: stingerlabs/ultralight-github-action@v1
        with:
          command: REPORT_COMMIT
          ultralight-url: https://2457b1f74502.ngrok-free.app
          ultralight-api-key: ul_7ffd53df0f84c822cfc6526e82ffbfd993d15186a00dd8cbc8c3176ebe997b5b
          commit-hash: ${{ github.sha }}
          pr-url: ${{ github.event.pull_request.html_url }}
          is-merge-commit: true
      - if: ${{ steps.report-commit.outputs.merge-allowed == 'true' }}
        name: Set status to success
        run: |
          echo "::success::This pull request can be merged."
          echo '${{ steps.report-commit.outputs.report-commit-data }}' | jq '.updatedSoftwarePartVersions'
          echo '${{ steps.report-commit.outputs.report-commit-data }}' | jq '.mergeAllowed.details'
      - if: ${{ steps.report-commit.outputs.merge-allowed != 'true' }}
        name: Set status to waiting and add annotation with full details
        run: |
          echo "::error::This pull request cannot be merged yet."
          echo '${{ steps.report-commit.outputs.report-commit-data }}' | jq '.updatedSoftwarePartVersions'
          echo '${{ steps.report-commit.outputs.report-commit-data }}' | jq '.mergeAllowed.details.releases.releasesWithErrors[].errors[]'
          exit 1
